apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: hotcold
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
